name = "ExampleJuliaPackage"
uuid = "0e0a2238-c02e-11e8-3c3b-1740289c94e7"
authors = ["Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.12"

[workspace]
projects = ["test"]
